from typing import Optional, Union

class Spi3Wire:
    _miso_pin = None
    _sck_pin = None
    _cs_pin = None
    _miso_pin_num: int = ...
    _sck_pin_num: int = ...
    _cs_pin_num: int = ...
    _cs_active_high: int = ...
    _cs_enable_reg: int = ...
    _cs_mask: int = ...
    _miso_enable_reg: int = ...
    _miso_mask: int = ...
    _sck_enable_reg: int = ...
    _sck_mask: int = ...
    _cmd_bits: int = ...
    _param_bits: int = ...

    def __init__(
        self,
        miso: int,
        sck: int,
        cs: int,
        cs_active_high: bool = False
    ):
        ...

    def __del__(self) -> None:
        ...

    def init(self, cmd_bits: int, param_bits: int) -> None:
        ...

    def deinit(self)-> None:
        ...

    def tx_param(
        self,
        cmd: int,
        params: Optional[Union[bytearray, bytes, memoryview]] = None
    ) -> None:
        ...


