
FILE(GLOB SUBDIRS ABSOLUTE ${CMAKE_CURRENT_LIST_DIR} ${CMAKE_CURRENT_LIST_DIR}/*)
FOREACH(SUBDIR ${SUBDIRS})
    IF(IS_DIRECTORY ${SUBDIR})
        include(${SUBDIR}/micropython.cmake)
    ENDIF()
ENDFOREACH()